# Site settings
title: Sandals
description: >
  Jet away to warmer climes for a truly luxurious holiday, make a Sandals resort your next stop. There’s never been a better time with up to 60% off, but hurry – sale ends 30th September!
baseurl: "/sandals" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site
sandals-url: "http://www.sandals.co.uk/specials/uk-offers?utm_medium=display&utm_source=secretescapes.co.uk&utm_campaign=Toy&utm_content=Text_Links"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, bower_components, bower.json, README.md]
