# Site settings
title: Sandals
client:
  name: Sandals
  link: https://www.sandals.co.uk/specials/uk-offers/?utm_medium=email&utm_source=secretescapes&utm_campaign=TOY
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Head for winter-sun and relax in your very own island paradise. Discover luxurious resorts spanning the finest shores of the Caribbean, set to indulge and pamper as you experience the island life.

# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/uk/2020/sandals" # the subpath of your site, e.g. /blog/
img:     "/uk/2020/sandals/_assets/img"
css:     "/uk/2020/sandals/_assets/css"
js:      "/uk/2020/sandals/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed