# Site settings
title: Sandals
client:
  name: Sandals
  link: "http://www.sandals.co.uk/specials/uk-offers/"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Discover luxurious all-inclusive Sandals resorts on the golden shores of the Caribbean – now half price. Your tropical getaway starts here...

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/sandals" # the subpath of your site, e.g. /blog/
img:     "/sandals/_assets/img"
css:     "/sandals/_assets/css"
js:      "/sandals/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed